# DEV PROFILE
server:
  port: 30000
  servlet:
    context-path: /it-net/api
spring:
  application:
    name: it-net-dev
  config:
    activate:
      on-profile: dev
## datasource:
  datasource:
    url: jdbc:mysql://localhost:3306/it_net
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
