# STAGING PROFILE
server:
  port: 30200
  servlet:
    context-path: /it-net/api
spring:
  application:
    name: it-net-sta
  config:
    activate:
      on-profile: sta
## datasource:
  datasource:
    url: jdbc:mysql://localhost:3306/clinical
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true